# Generated by Django 2.2.4 on 2019-08-30 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CenterArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='文章标题')),
                ('leader', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='引题')),
                ('author', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='作者')),
                ('data_entry_staffer', models.CharField(blank=True, max_length=20, null=True, verbose_name='录入')),
                ('editor', models.CharField(blank=True, max_length=20, null=True, verbose_name='编辑')),
                ('facade_pic_url', models.ImageField(blank=True, null=True, upload_to='media/articles/%Y/%M', verbose_name='外挂图')),
                ('article_pic', models.ImageField(blank=True, null=True, upload_to='media/articles/%Y/%M', verbose_name='文章内图')),
                ('clicknum', models.IntegerField(default=0, verbose_name='点击数')),
                ('managing_editor', models.CharField(blank=True, max_length=20, null=True, verbose_name='责任编辑')),
                ('filelink', models.CharField(blank=True, max_length=100, null=True, verbose_name='文章地址')),
                ('videolink', models.ImageField(blank=True, null=True, upload_to='media/articles/%Y/%M', verbose_name='视频链接')),
                ('contentpart', models.CharField(blank=True, max_length=252, null=True, verbose_name='文章摘要')),
                ('date_created', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('last_update', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('date_issued', models.DateTimeField(default=datetime.datetime.now, verbose_name='发布时间')),
                ('hit', models.IntegerField(default=500, verbose_name='点击数')),
                ('hothit', models.IntegerField(choices=[(0, '不是焦点图'), (1, '首页焦点图'), (2, '二级页面的焦点图'), (3, '三级页面的焦点图')], default=0, verbose_name='焦点图')),
                ('is_avail', models.BooleanField(default=False, verbose_name='是否发布')),
                ('is_audited', models.BooleanField(default=False, verbose_name='是否审核')),
                ('has_article_pic', models.BooleanField(default=False, verbose_name='是否包含图片')),
                ('source', models.CharField(blank=True, default='网络摘录', max_length=20, null=True, verbose_name='文章来源')),
                ('keyword', models.CharField(blank=True, max_length=252, null=True, verbose_name='关键字')),
                ('reserve', models.CharField(blank=True, max_length=252, null=True, verbose_name='备注')),
                ('content', models.CharField(blank=True, max_length=10, null=True, verbose_name='文章内容')),
                ('important_opt', models.BooleanField(default=False, verbose_name='是否突出显示')),
                ('quick_response_code', models.BooleanField(default=False, verbose_name='返回码')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'db_table': 'center_article',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CenterHeadLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operate_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('photo_url', models.ImageField(blank=True, null=True, upload_to='media/headline/%Y/%M')),
                ('sign', models.BooleanField(default=True, verbose_name='是否显示')),
                ('site', models.IntegerField()),
                ('title', models.CharField(blank=True, max_length=60, null=True, verbose_name='头条标题')),
                ('top_program_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '头条',
                'verbose_name_plural': '头条',
                'db_table': 'center_head_line',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_title', models.CharField(default='', max_length=20, verbose_name='栏目名称')),
                ('program_desc', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='栏目描述')),
                ('is_leaf', models.BooleanField(default=True, verbose_name='是否为终节点')),
                ('is_avail', models.BooleanField(default=True, verbose_name='是否可用')),
                ('is_show', models.BooleanField(default=False, verbose_name='是否在前台页面显示')),
                ('domain_name', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='栏目类')),
                ('date_created', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('skin', models.CharField(blank=True, max_length=20, null=True, verbose_name='栏目SKIN')),
                ('sort_field', models.IntegerField(default=1, verbose_name='排序权重')),
                ('frequency', models.IntegerField(default=1, verbose_name='使用频率')),
                ('category', models.IntegerField(choices=[(1, '省(直辖市)'), (2, '地市(区县)'), (3, '频道')], default=1, verbose_name='栏目类别')),
                ('program_level', models.IntegerField(default=1, verbose_name='栏目级别')),
                ('first_letter', models.CharField(blank=True, default='', max_length=6, null=True, verbose_name='栏目首字母')),
                ('specialUrl', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='栏目外链接')),
                ('program_pic_url', models.ImageField(blank=True, default='', null=True, upload_to='media/images/adv/')),
                ('is_channel', models.BooleanField(default=False, verbose_name='是否为子频道')),
            ],
            options={
                'verbose_name': '栏目列表',
                'verbose_name_plural': '栏目列表',
                'db_table': 'center_program',
                'managed': False,
            },
        ),
    ]
