# Generated by Django 2.2.4 on 2019-08-30 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True, verbose_name='广告位')),
                ('ad_type', models.CharField(blank=True, choices=[('static', '静态'), ('flow', '滚动'), ('flash', '焦点图')], default='static', max_length=10, null=True, verbose_name='广告类型')),
                ('local_div', models.CharField(blank=True, max_length=20, null=True, verbose_name='位置')),
                ('widthorspeed', models.CharField(blank=True, max_length=5, null=True, verbose_name='宽度/速度')),
                ('heightorvisiable', models.CharField(blank=True, max_length=5, null=True, verbose_name='高度/条数')),
                ('direction', models.CharField(blank=True, max_length=5, null=True, verbose_name='方向')),
            ],
            options={
                'verbose_name': '广告位',
                'verbose_name_plural': '广告位',
                'db_table': 'center_ad_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Advment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='广告名称')),
                ('photo_url', models.ImageField(blank=True, null=True, upload_to='media/adv/%Y/%M', verbose_name='图片')),
                ('linkUrl', models.CharField(blank=True, max_length=100, null=True, verbose_name='外连接')),
                ('operate_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('sign', models.BooleanField(default=True, verbose_name='是否启用')),
                ('local_on_page', models.IntegerField(default=1, verbose_name='显示顺序')),
            ],
            options={
                'verbose_name': '广告',
                'verbose_name_plural': '广告',
                'db_table': 'center_advertisment',
                'managed': False,
            },
        ),
    ]
